### PR TITLE
Sync ros2 with master

### PR DESCRIPTION
**Pull request by sloretz**
This brings the message definitions on the ros2 branch up to date with the `kinetic-devel` branch.

### CODE REVIEW

**Comment by Kukanani** [comment]
Hi Shane, thanks for the PR. This is probably all good, but just for reference - the current kinetic branch represents breaking changes compared to previous kinetic branches because of new message fields. I need to move those breaking changes to a new master branch. 

If the goal is to simply update the ROS2 branch to the latest and greatest, this is the correct set of changes to pull in. But if you are trying to make the ROS2 branch sync the actual (i.e. released) kinetic functionality, then we need to be more careful.

Can you confirm which of these two is the PR's intent?

I'll see if I can get to testing this (and doing the above branch edits) over the weekend.

**Comment by sloretz** [comment]
I think my intent is to get the latest and greatest. I'd like to use the version of `ObjectHypothesis` where `id` is a string instead of an int.

**Comment by Kukanani** [comment]
Sounds good.

I reverted the breaking changes to kinetic-devel, putting them in `master` instead (#33), and renamed to this issue to be "sync with master" since that's now the correct description. It seems to have broken this PR in the process, but honestly I'm not sure how.

Sorry for the extra headache, I should have done this sooner.

**Comment by Kukanani** [comment]
I've verified that this branch builds on a clean Dashing install w/`colcon`.

**Comment by sloretz** [comment]
>  It seems to have broken this PR in the process, but honestly I'm not sure how.

Should be fixed now. Tthe PR is a merge of `master` into `ros2` plus the commit 7928732 which makes the test work in ROS 2.

**Comment by Kukanani** [comment]
LGTM

**Pull request merged**
